CREATE TABLE weapons (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  damageDie TEXT NOT NULL,
  damageBonus INTEGER NOT NULL,
  special TEXT,
  range INTEGER,
  fireRate INTEGER,
  cost INTEGER,
  description TEXT
);